### ISSUE TITLE
It is amazing!

### ISSUE THREAD

**Issue by jonataslaw** [DrDejaVuNG/get-website#1]
Thank you for your hard work, it is amazing!
I have the domain getx.dev, so I can link this github to deploy the documentation in there. 
There is an easy way to add internacionalization to the website?

**Comment by DrDejaVuNG** [comment]
Thank You!!!, I had Dm'd you on Telegram but I'm guessing you didn't get to see it, Yes, there is an easy way to add internalizations as well as documentation versions. About the domain name that would be perfect, I tried buying Get or Getx related domains and they were all taken.
